name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install GCC 14
      run: "sudo apt update && sudo apt install gcc-14"
      shell: bash
    - name: make
      working-directory: ./extras/tests
      run: make unittest
